version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeFolio-server
    depends_on:
      - db
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:${DB_PORT}/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod
    restart: always
    networks:
      - codeFolio-net

  db:
    image: mysql:8.4.4
    container_name: codeFolio-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      --port=${DB_PORT} --max_allowed_packet=32M
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - codeFolio-net

volumes:
  db-data:

networks:
  codeFolio-net:
    driver: bridge
