services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeFolio-server
    depends_on:
      - codeFolio-database
    ports:
      - "${SPRING_PORT}:8080"
    env_file:
      - .env
    restart: always
    networks:
      - codefolio-net

  codeFolio-database:
    image: mysql:8.4.4
    container_name: codeFolio-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - codefolio-data:/var/lib/mysql
    restart: always
    networks:
      - codefolio-net

volumes:
  codefolio-data:

networks:
  codefolio-net:
    driver: bridge
